[package]
name = "y25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
include_dir = "0.7.3"
md5 = "0.7.0"
regex = "1.9.4"
